name: publish-snapshot

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create a snapshot from'
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'

      - uses: ./.github/actions/prepare
        with:
          cache_fresh_start: 'true'

      - name: Create and Publish Snapshot
        run: |
          yarn changeset version --snapshot canary
          yarn changeset publish --tag canary --no-git-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
# name: publish-snapshot

# on:
#   push:
#     branches-ignore:
#       - main

# concurrency: ${{ github.workflow }}-${{ github.ref }}

# jobs:
#   release:
#     name: Release
#     runs-on: ubuntu-latest
#     steps:
#       # Setup
#       - name: Checkout Repo
#         uses: actions/checkout@v3

#       # Build
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '18.13.0'
#       - uses: ./.github/actions/prepare
#         with:
#           cache_fresh_start: 'true'

#       - name: Create Snapshot Pull Request or Publish to npm
#         id: changesets
#         uses: changesets/action@v1
#         with:
#           version: yarn changeset version --snapshot canary
#           publish: yarn changeset publish --tag canary --no-git-tag
#           title: 'chore(snapshot): Packages snapshots'
#           commit: 'chore(snapshot): releasing snapshot preview'
#           createGithubReleases: false
#         env:
#           GITHUB_TOKEN: ${{ secrets.GAT }}
#           NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
