name: publish-snapshot

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to create a snapshot from'
        required: true

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'

      - uses: ./.github/actions/prepare
        with:
          cache_fresh_start: 'true'

      - name: Set up npm authentication
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: Create and Publish Snapshot
        run: |
          yarn changeset version --snapshot canary
          yarn changeset publish --tag canary --no-git-tag
        env:
          GITHUB_TOKEN: ${{ secrets.GAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
