name: publish-snapshot

on:
  push:
    branches-ignore:
      - $default-branch

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      # Setup
      - name: Checkout Repo
        uses: actions/checkout@v3

      # Build
      - uses: actions/setup-node@v3
        with:
          node-version: '18.13.0'
      - uses: ./.github/actions/prepare
        with:
          cache_fresh_start: 'true'

      - name: Create Snapshot Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          version: yarn changeset version --snapshot SNAPSHOT
          publish: yarn changeset publish --tag SNAPSHOT --no-git-tag
          title: 'chore(snapshot): Packages snapshots'
          commit: 'chore(snapshot): releasing snapshot preview'
          createGithubReleases: false
        env:
          GITHUB_TOKEN: ${{ secrets.GAT }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
